import Sidebar from "@/app/_components/dashboard/sidebar";
import type { Metadata } from "next";

interface DashboardLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Dashboard | Build&Showcase",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }: DashboardLayoutProps) {
  return (
    <>
      <div className="grid grid-cols-[auto_1fr]">
        <Sidebar />
        <main className="h-full w-full">{children}</main>
      </div>
    </>
  );
}
